### PR TITLE
Update iOS deployment target to 9.0 for Xcode 12

### PR DESCRIPTION
**Pull request by GeroHerkenrath**
Hello!

I took the liberty to update the project a bit to cut off iOS 8 as deployment target. The reason for this would be that starting with Xcode 12, iOS 8 is no longer supported by the build system and so this throws some annoying warnings (well, one for Telegraph itself, the others come from its dependencies which I will also update in that manner).

I'm not sure how many people would still target iOS 8 and rely on this package, so ultimately it is up to you to decide whether you want to merge this or not. I'll use my forks if you can't merge in that case.

Btw, I also updated the .`podspec` with a new version (`0.29.0`, so semantic versioning now) for those who use Telegraph as a pod, but that would naturally require you to create an according tag and push to the cocoapods repo. I'd encourage such a tag also for the SPM users (like myself) so we don't have to specify the `master` branch, but can use tags instead. 

I also noticed that the dependency requirements are laxer than in the Package.swift definition, so I modified the latter to match the pod's definition. This will also result in people automatically updating Telegraph's dependencies once they have the same Xcode 12 update. The stricter version constraints would have prevented that as I plan to propose an increment of the MINOR version part of those libs.

Lastly I'd like to say that I really like your work, I use Telegraph in my UI tests and it works great!

### CODE REVIEW

**Comment by GeroHerkenrath** [comment]
Damn, I just realized I forgot to also bring the `Cartfile` in sync with the `Telegraph.podspec` and `Package.swift` files... I have never used Carthage myself, should I simply do that or would it be better to wait for the dependencies to also be updated and include updated minimum version numbers?

**Comment by satoko150** [comment]
I think your pull request is now mandatory because the deployment target of CocoaAsyncSocket, which is one of the dependencies, has been updated to 9.0.

**Comment by GeroHerkenrath** [comment]
Interesting point, I am curious how SPM/Xcode would handle it if a dependency has a higher deployment target than is specified in the package file for the library itself. I cannot try that out atm, though as I am not in the office for the rest of the week. 

They (`CocoaAsyncSocket` that is) didn't follow my suggestion to increase the minor instead of the patch part of the new version number (which is completely fine), so I guess I could also change this PR and use 7.6.5 instead of 7.5 or a broader one that catches it. I could also modify the Carthage file, but as said, that would have to wait for a bit...

**Comment by yliu342** [comment]
Seems reasonable to drop support for iOS 8 given it is 2021 now.
With SPM we can force to use an older version (7.6.4) of `CocoaAsyncSocket` which will compile and run properly but the latest update to `CocoaAsyncSocket` has replace the usage of `UIWebview` with `WKWebview`. If you used the older version of `CocoaAsyncSocket` then I think you will have a hard time submit to App Store. 
@yvbeek any thoughts on this?

**Comment by yvbeek** [comment]
Thank you for the PR. Yes I agree, we should be able to drop iOS 8 support.

**Pull request merged**
